@startuml controlled_map_generator_class_diagram
skinparam linetype ortho

package SistemaGerenciadorMapaProdutosControlados {

    class Address <<entity>> {
        - UUID id
        - String publicPlace
        - String number
        - String neighborhood
        - String city
        - String state
        - String cep
        - String complement
    }

    class Company <<entity>>{
        - UUID id
        - String corporateReason
        - String cnpj
        - String phone
        - Address address
    }

    class Supplier <<entity>>{
        - UUID id
        - String corporateReason
        - String cnpj
        - String phone
        - Address address
    }

    class User <<entity>>{
        - UUID id
        - String name
        - String cpf
        - String rg
        - String phone
        - String email
        - String password
        - String profilePictureUrl
        - boolean isActive
        - Address address
        - List<Company> companies
    }

    class Product <<entity>>{
        - UUID id
        - String name
        - String measurementUnit
        - Company company
    }

    class Invoice <<entity>> {
        - UUID id
        - String invoiceNumber
        - String path
        - Supplier supplier
        - User registrationUser
        - Company company
    }

    class ProductMovimentationIn <<entity>>{
        - UUID id
        - BigDecimal quantity
        - DateTime purchaseDate
        - Invoice invoice
        - Product product
        - Supplier supplier
        - User registrationUser
        - Company company
    }

    class ProductMovimentationOut <<entity>>{
        - UUID id
        - BigDecimal quantity
        - String destination
        - DateTime consumptionDate
        - Product product
        - User registrationUser
        - Company company
    }

    class ProductMapHistoryProduct <<entity>>{
        - UUID id
        - BigDecimal remainingQuantity
        - BigDecimal purchasedQuantity
        - BigDecimal totalConsumed
        - BigDecimal totalLost
        - BigDecimal finalQuantity
        - ProductMapHistory productMapHistory
        - Product product
    }

    class ProductMapHistory <<entity>>{
        - UUID id
        - DateTime generatedDate
        - boolean isOriginal
        - Company company
    }

    class AddressManager <<control>>{
        + getFullAddressText(UUID id): String
        + updateAddressInformation(Address address): Boolean
        + addNewAddress(Address address): Boolean
    }

    class CompanyManager <<control>>{
        + createOrUpdateCompanyProfile(Company company): Boolean
        + getCompanyInfo(UUID id): Company
    }

    class SupplierManager <<control>>{
        + getSupplierInfo(UUID id): Supplier
        + saveSupplier(Supplier supplier): UUID
        + bulkCreateSuppliersIfNotExists(List<Supplier> suppliers): Boolean
        + deleteSupplier(UUID id): Boolean
    }

    class UserManager <<control>>{
        + getLoggedUser(UUID id): User
        + authenticateUser(String email, String password): User
        + updateUserProfile(User user): Boolean
        + resetPassword(UUID id, String newPassword): Boolean
        + changeProfilePicture(UUID id, String urlLink): Boolean
    }

    class ProductManager <<control>>{
        + getProductInfo(UUID id): Product
        + getManufacturerInfo(UUID id): Company
        + changeMeasurementUnit(UUID id, String newMeasurementUnit): Boolean
        + saveProduct(Product product): UUID
    }

    class InvoiceManager <<control>>{
        + getInvoiceFullData(UUID id): Invoice
        + getInvoiceBySupplier(Supplier supplier): List<Invoice>
        + importNewInvoice(String xmlFile): UUID
        + extractSuppliers(Invoice invoice): List<Supplier>
    }

    class ProductMovimentationManager <<control>>{
        + getListOfProductsByDate(DateTime purchaseDate): List<Product>
        + addNewProductMovimentationIn(ProductMovimentationIn movimentation): Boolean
        + addNewProductConsumption(ProductMovimentationOut movimentation): String
        + sumAllConsumptionsByDate(DateTime consumptionDate): Float
        + notifyLowStockQuantity(): void
    }

    class ProductMapHistoryManager <<control>>{
        + getAllProductsFromMap(ProductMapHistory map): List<ProductMapHistoryProduct>
        + saveProductMapHistory(ProductMapHistory productMap): Boolean
        + downloadMap(UUID id): Byte[]
        + deleteProductMap(UUID id): Boolean
        + getAllMapsGeneratedByCompany(Company company): List<ProductMapHistory>
        + registerAnyModifications(): void
    }

    Company "1" *-- "1" Address : has
    User "1" *-- "1" Address : lives-at
    User "1" *-- "*" Company : works-for
    Supplier "1" *-- "1" Address : located-at
    Invoice "1" *-- "1" Supplier : issued-by >
    Invoice "1" *-- "1" User : imported-by >
    ProductMovimentationIn "1..*" *-- "1" Invoice : part-of >
    ProductMovimentationIn "1..*" *-- "1" Product : contains >
    ProductMovimentationIn "1" *-- "1" Supplier : from >
    ProductMovimentationIn "1..*" *-- "1" User : registered-by >
    ProductMovimentationOut "1..*" *-- "1" Product : contains >
    ProductMovimentationOut "1..*" *-- "1" User : registered-by >
    ProductMapHistoryProduct "1..*" *-- "1" ProductMapHistory : part-of >
    ProductMapHistoryProduct "1..*" *-- "1" Product : includes >
    Product "1" *-- "1" Company : produced-by
}
@enduml
