@startuml controlled_map_generator_use_case_diagram
left to right direction
skinparam packageStyle rect
skinparam actorStyle hollow
skinparam linetype polyline

actor Diretor <<humano>>
actor Operador <<humano>>
actor API <<sistema>>

Diretor <|-left- Operador

package "Sistema gerenciador de mapas\nde produtos controlados" {
    usecase "Criar modelo\nde mapa" as UC1
    usecase "Editar\nmodelo" as UC2
    usecase "Apagar\nmodelo" as UC3
    usecase "Selecionar\nmodelo de mapa" as UC4
    usecase "Efetuar\ndownload" as UC5
    usecase "Armazenar dados\nde notas fiscais" as UC7
    usecase "Atualizar valores\nde estoque" as UC8
    usecase "Extrair\nfornecedores" as UC9
    usecase "Importar\nXML NFe" as UC10
    usecase "Registrar consumo\nde produtos" as UC11
    usecase "Editar\nfornecedor" as UC12
    usecase "Apagar\nfornecedor" as UC13
    usecase "Selecionar\nfornecedor" as UC14
    usecase "Adicionar\nfornecedor" as UC15
    usecase "Autenticar\nna aplicação" as UC16
    usecase "Alertar quantidade\nde produtos\nem estoque" as UC17
}

Diretor --> UC1
Diretor --> UC4
Diretor --> UC10

UC4 <|-- UC2 : <<extends>>
UC4 <|-- UC3 : <<extends>>
UC4 <|-- UC5 : <<extends>>

UC1 --> UC2 : <<include>>

UC10 --> UC7 : <<include>>
UC10 --> UC8 : <<include>>
UC10 --> UC9 : <<include>>

Operador --> UC11
Operador --> UC14
Operador --> UC15
Operador --> UC16

UC11 --> UC17 : <<include>>

UC14 <|-- UC12 : <<extends>>
UC14 <|-- UC13 : <<extends>>

API -up-> UC7
API -up-> UC8
API -up-> UC9
API -up-> UC17

@enduml
